[tool.poetry]
name = "pandas-cast-speed-test"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.*"
pandas = "2.1.0"
numpy = "1.25.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
